spring:
  datasource:
    username: root
    password: yourpassrod
    url: jdbc:mysql://127.0.0.1:3306/user?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 1
    password: xxxxx
    host: 127.0.0.1
  mail:
    host: smtp.qq.com #邮件服务器地址
    port: 465 #端口号
    username: xxxxxxx@qq.com
    password: xxxxxxx
    default-encoding: UTF-8 #默认编码格式
    properties:
      mail:
        debug: true #启动debug调试
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory #SSL连接配置
  flyway:
    enabled: true # 开启flyway
    clean-disabled: true # 禁止清理数据表
    table: flyway_schema_history # 版本控制信息表名，默认为flyway_schema_history
    out-of-order: false # 是否允许不按顺序迁移
    baseline-on-migrate: true # 如果数据库不是空表，需要设置为true，否则启动报错
    baseline-version: 1 # 和baseline-on-migrate搭配使用，小于此版本的不执行
    # schemas: 不设置使用默认Spring连接数据的地址和数据库
    validate-on-migrate: true # 执行迁移时是否自动调用验证
    locations: classpath:db/migration
  # 配置数据库，flyway那边就无需再进行数据的配置了
structure:
  basic:
    address-list:
    - http://localhost:5173/src/assets/test.zip
    enable-view: true
  oauth:
    resource:
      resource-id: user
      antMatchers:
        unAuthenticated:
        # 不经过身份验证的接口
        - /doc.html
        - /webjars/**
        - /swagger-resources/**
        - /v2/api-docs/**
        - /web-api/auth-code/**
        - /open-api/**
  user:
    sms-login-template-code: ss
    sms-register-template-code: ss
    sms-reset-password-template-code: ss
    sms:
      product: sms
      access-key-id: xxxxxxxx
      access-key-secret: xxxxxxxxxxxx
      sign-name:  sss
      endpoint-name: dysmsapi.aliyuncs.com
      domain: ss
      region-id:  ss
      enable: false
  log:
    aop:
      expression: execution(public * cn.structured.user.controller..*Controller.*(..))
swagger:
  title: 用户中心API
  description: structure-user
  version: v1.0.1