spring:
  datasource:
    username: oauth
    password: 3MHFsHGM7kcN8fdf
    url: jdbc:mysql://39.97.124.2:3306/oauth?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 1
    password: 8023.521
    host: 39.97.124.2
  flyway:
    enabled: true # 开启flyway
    clean-disabled: true # 禁止清理数据表
    table: flyway_schema_history # 版本控制信息表名，默认为flyway_schema_history
    out-of-order: false # 是否允许不按顺序迁移
    baseline-on-migrate: true # 如果数据库不是空表，需要设置为true，否则启动报错
    baseline-version: 1 # 和baseline-on-migrate搭配使用，小于此版本的不执行
    # schemas: 不设置使用默认Spring连接数据的地址和数据库
    validate-on-migrate: true # 执行迁移时是否自动调用验证
    locations: classpath:db/migration
  # 配置数据库，flyway那边就无需再进行数据的配置了
structure:
  oauth:
    jwt:
      jks-path: yunjida.jks
      key-pair: yunjida
      password: yueyankeji@yunjida
    adapters:
      weChat:
        accessKey: aaa
        secretKey: bbbb
      dingTalk:
        accessKey: ccc
        secretKey: ddd
  log:
    aop:
      expression: execution(public * cn.structured.oauth.server.controller..*Controller.*(..))
  ribbon:
    enable: true
    server:
    - id: user-center
      host: 127.0.0.1
      port: 17001
